In [6]:
#Q1数组创建与属性查看
import numpy as np
#创建从1到12的一维数组
arr = np.arange(1,13)
#重塑为3行4列的二维数组
arr_reshaped = arr.reshape(3,4)
#打印数组属性
print("数组维度（ndim）：", arr_reshaped.ndim)
print("数组形状（shape）：", arr_reshaped.shape)
print("元素总个数（size）：", arr_reshaped.size)

数组维度（ndim）： 2
数组形状（shape）： (3, 4)
元素总个数（size）： 12


In [ ]:
#Q2.数据类型转换
import numpy as np
#创建浮点数数组
arr_float = np.array([1.5, 2.6, 3.7,4.8])
#转换为int32类型
arr_int = arr_float.astype(np.int32)
#打印转换前后的数组和数据类型
print("转换前数组：", arr_float)
print("转换前数据类型：", arr_float.dtype.name)
print("转换后数组：", arr_int)
print("转换后数据类型：", arr_int.dtype.name)

转换前数组： [1.5 2.6 3.7 4.8]
转换前数据类型： float64
转换后数组： [1 2 3 4]
转换后数据类型： int32


In [4]:
#Q3.二维数组的切片操作
import numpy as np
#创建题目给定的二维数组
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
#切片操作：前两行、第2-3列
sub_arr = arr[0:2, 1:3]
#打印结果
print(sub_arr)

[[2 3]
 [6 7]]


In [14]:
#Q4.花式索引与布尔索引
import numpy as np
#给定的一维数组
arr =np.array([10,15,20,25,30,35])
#花式索引：提取索引为0,2,4的元素
fancy_index_result = arr[[0, 2, 4]]
print( fancy_index_result)
#布尔索引：提取大于20的元素
bool_index_result=arr[arr>20]
print( bool_index_result)

[10 20 30]
[25 30 35]


In [16]:
a=arr[5]
print(a)
a=arr[-1]
print(a)

35
35


In [11]:
#Q5.数组运算与广播机制
import numpy as np
#创建形状为(3,4)的全0数组
arr_a = np.zeros((3,4))
#创建一维数组
arr_b = np.array([1,2,3,4])
#广播机制
result = arr_a + arr_b
#打印结果
print(result)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [13]:
#Q6通用函数的应用
import numpy as np
x=np.array([1,4,9,16])
y=np.array([2,1,4,5])
sqrt_x = np.sqrt(x)
print("平方根:", sqrt_x)
result = np.maximum(sqrt_x,y)
print("最大值:", result)

平方根: [1. 2. 3. 4.]
最大值: [2. 2. 4. 5.]


In [ ]:
#Q7 数组的转置
import numpy as np
#创建形状为(2,3,4)的三维数组
arr = np.arange(24).reshape((2,3,4))
print("原数组的形状：", arr.shape)
#将轴顺序转换为(1,0,2)
transposed_arr = arr.transpose((1,0,2))
print("转置后数组的形状：", transposed_arr.shape)

原数组的形状： (2, 3, 4)
转置后数组的形状： (3, 2, 4)


In [10]:
#Q8 条件逻辑运算
import numpy as np
arr_x = np.array([1,5,7])
arr_y = np.array([2,6,8])
arr_con = np.array([True,False,True])
#使用np.where()按条件选择元素
result = np.where(arr_con,arr_x,arr_y)
print("结果数组：",result)
a=arr_x*arr_y
print(a)
b=np.dot(arr_x,arr_y)
print(b)

结果数组： [1 6 7]
[ 2 30 56]
88


In [8]:
#Q9 统计运算与排序
import numpy as np
arr = np.array([[6,2,7], [3,6,2], [4,3,2]])
print("原数组：")
print(arr)
#计算算术平均值
mean_val = arr.mean()
print("\n数组所有元素的算术平均值：",mean_val)
#按列（axis=0）从小到大排序
arr.sort(axis=0)
print("\n按列排序后的数组：")
print(arr)

原数组：
[[6 2 7]
 [3 6 2]
 [4 3 2]]

数组所有元素的算术平均值： 3.888888888888889

按列排序后的数组：
[[3 2 2]
 [4 3 2]
 [6 6 7]]


In [5]:
#Q10 随机数生成与矩阵点积
import numpy as np
#设置随机数种子为10
np.random.seed(10)
#生成两个形状为(2,2)的随机矩阵A和B，服从[0,1)均匀分布
A = np.random.rand(2,2)
B = np.random.rand(2,2)
#计算矩阵A和B的点积
dot_product = np.dot(A,B)

print("矩阵A：")
print(A)
print("\n矩阵B：")
print(B)
print("\n矩阵A和B的点积：")
print(dot_product)

矩阵A：
[[0.77132064 0.02075195]
 [0.63364823 0.74880388]]

矩阵B：
[[0.49850701 0.22479665]
 [0.19806286 0.76053071]]

矩阵A和B的点积：
[[0.38861894 0.18917279]
 [0.46418833 0.71193035]]
